version: 2

jobs:
  build:
    working_directory: ~/parabolic
    docker:
      - image: quay.io/fenicsproject/stable:current
    steps:
      - setup_remote_docker:
          reusable: true
      - run: apt-get update
      - run: apt-get install -y python-pip
      - run: apt-get install -y git
      - run: pip install pytest pytest-cov
      - checkout
      - run: pip install .
      # The actual test
      - run: MPLBACKEND=Agg pytest --cov parabolic
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
