version: 2

jobs:
  build:
    working_directory: ~/parabolic
    docker:
      # https://fenicsproject.org/download/
      - image: quay.io/fenicsproject/stable:current
    steps:
      - run: apt-get update
      - run: apt-get install -y python-pip
      - run: sudo -H pip2 install -U pytest pytest-cov pylint
      - run: apt-get install -y git
      - checkout
      - run: pip2 install .
      # lint
      - run: pylint parabolic/
      - run: pylint tests/*.py
      # The actual test
      - run: PYTHONPATH=$PWD:$PYTHONPATH MPLBACKEND=Agg pytest --cov parabolic
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
